name: Trello API Tests

on:
  push:
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_TOKEN: ${{ secrets.POSTMAN_TOKEN }}
        run: |
          newman run "Trello_collection.json" \
            -e "Trello_Prod_environment" \
            --env-var "api_key=${POSTMAN_API_KEY}" \
            --env-var "token=${POSTMAN_TOKEN}"
      
